apiVersion: apps/v1
kind: Deployment
metadata:
  name: arabic-names-mcp-server
  namespace: arabic-names
  labels:
    app: arabic-names-mcp-server
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: arabic-names-mcp-server
  template:
    metadata:
      labels:
        app: arabic-names-mcp-server
        version: v1
    spec:
      containers:
      - name: mcp-server
        image: ghcr.io/sahebsoft/arabic-names/mcp-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        envFrom:
            - secretRef:
                name: elasticsearch-master-credentials
            - configMapRef:
                name: elasticsearch-config
        env:
        - name: ELASTIC_CA_CERT
          valueFrom:
            secretKeyRef:
              name: elasticsearch-master-certs
              key: ca.crt
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - node
            - -e
            - "process.exit(0)"
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1001
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      imagePullSecrets:
        - name: ghcr-secret
      securityContext:
        fsGroup: 1001
      restartPolicy: Always